project:
  title: a soft, pastel lilac/lavender color scheme for RevealJS presentations with an academic, professional feel. The palette should be light and airy with subtle gradients. Quarto revealjs Theme

